development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: rails_app_dev
  pool: 5
  username: root
  password: dummy123
  socket: /var/run/mysqld/mysqld.sock
test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: rails_app_test
  pool: 5
  username: root
  password: dummy123
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: rails_app_production
  pool: 5
  username: root
  password: dummy123
  socket: /var/run/mysqld/mysqld.sock
